// @generated by
//     __             _____     _                 ___ ___
//  _ |  |___ ___ ___|   __|___| |_ ___ _____  __| | |_  |
// | |_| |_ -| . |   |__   |  _|   | -_|     ||. |_  |  _|
// |_____|___|___|_|_|_____|___|_|_|___|_|_|_|___| |_|___|
// v0.8.9                          -- www.JsonSchema42.org
import * as types from "./types.js";
export function isDraft202012Schema(value: unknown): value is types.Draft202012Schema {
if(!_isMapDraft202012Schema(value) && !_isBooleanDraft202012Schema(value) && !_isAllOfDraft202012Schema(value)) {
return false;
}
return true;
}
function _isMapDraft202012Schema(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
switch(propertyName) {
case "definitions":
if(!isDefinitions(propertyValue)) {
return false;
}
break;
case "dependencies":
if(!isDependencies(propertyValue)) {
return false;
}
break;
case "$recursiveAnchor":
if(!isRecursiveAnchor(propertyValue)) {
return false;
}
break;
case "$recursiveRef":
if(!isRecursiveRef(propertyValue)) {
return false;
}
break;
}
}
return true;
}
function _isBooleanDraft202012Schema(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
function _isAllOfDraft202012Schema(value: unknown): value is unknown {
if(!isAllOf0(value)) {
return false;
}
if(!isAllOf1(value)) {
return false;
}
if(!isAllOf2(value)) {
return false;
}
if(!isAllOf3(value)) {
return false;
}
if(!isAllOf4(value)) {
return false;
}
if(!isAllOf5(value)) {
return false;
}
if(!isAllOf6(value)) {
return false;
}
return true;
}
export function isDefinitions(value: unknown): value is types.Definitions {
if(!_isMapDefinitions(value)) {
return false;
}
return true;
}
function _isMapDefinitions(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
if(!isDefinitionsAdditionalProperties(propertyValue)) {
return false;
}
}
return true;
}
export function isDependencies(value: unknown): value is types.Dependencies {
if(!_isMapDependencies(value)) {
return false;
}
return true;
}
function _isMapDependencies(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
if(!isDependenciesAdditionalProperties(propertyValue)) {
return false;
}
}
return true;
}
export function isRecursiveAnchor(value: unknown): value is types.RecursiveAnchor {
if(!_isReferenceRecursiveAnchor(value)) {
return false;
}
return true;
}
function _isReferenceRecursiveAnchor(value: unknown): value is unknown {
if(!isAnchorString(value)) {
return false;
}
return true;
}
export function isRecursiveRef(value: unknown): value is types.RecursiveRef {
if(!_isReferenceRecursiveRef(value)) {
return false;
}
return true;
}
function _isReferenceRecursiveRef(value: unknown): value is unknown {
if(!isUriReferenceString(value)) {
return false;
}
return true;
}
export function isAllOf0(value: unknown): value is types.AllOf0 {
if(!_isReferenceAllOf0(value)) {
return false;
}
return true;
}
function _isReferenceAllOf0(value: unknown): value is unknown {
if(!isCore(value)) {
return false;
}
return true;
}
export function isAllOf1(value: unknown): value is types.AllOf1 {
if(!_isReferenceAllOf1(value)) {
return false;
}
return true;
}
function _isReferenceAllOf1(value: unknown): value is unknown {
if(!isApplicator(value)) {
return false;
}
return true;
}
export function isAllOf2(value: unknown): value is types.AllOf2 {
if(!_isReferenceAllOf2(value)) {
return false;
}
return true;
}
function _isReferenceAllOf2(value: unknown): value is unknown {
if(!isUnevaluated(value)) {
return false;
}
return true;
}
export function isAllOf3(value: unknown): value is types.AllOf3 {
if(!_isReferenceAllOf3(value)) {
return false;
}
return true;
}
function _isReferenceAllOf3(value: unknown): value is unknown {
if(!isValidation(value)) {
return false;
}
return true;
}
export function isAllOf4(value: unknown): value is types.AllOf4 {
if(!_isReferenceAllOf4(value)) {
return false;
}
return true;
}
function _isReferenceAllOf4(value: unknown): value is unknown {
if(!isMetaData(value)) {
return false;
}
return true;
}
export function isAllOf5(value: unknown): value is types.AllOf5 {
if(!_isReferenceAllOf5(value)) {
return false;
}
return true;
}
function _isReferenceAllOf5(value: unknown): value is unknown {
if(!isFormatAnnotation(value)) {
return false;
}
return true;
}
export function isAllOf6(value: unknown): value is types.AllOf6 {
if(!_isReferenceAllOf6(value)) {
return false;
}
return true;
}
function _isReferenceAllOf6(value: unknown): value is unknown {
if(!isContent(value)) {
return false;
}
return true;
}
export function isDefinitionsAdditionalProperties(value: unknown): value is types.DefinitionsAdditionalProperties {
if(!_isReferenceDefinitionsAdditionalProperties(value)) {
return false;
}
return true;
}
function _isReferenceDefinitionsAdditionalProperties(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isDependenciesAdditionalProperties(value: unknown): value is types.DependenciesAdditionalProperties {
if(!_isAnyOfDependenciesAdditionalProperties(value)) {
return false;
}
return true;
}
function _isAnyOfDependenciesAdditionalProperties(value: unknown): value is unknown {
if(isAdditionalPropertiesAnyOf0(value)) {
return true;
}
if(isAdditionalPropertiesAnyOf1(value)) {
return true;
}
return false;
}
export function isAdditionalPropertiesAnyOf0(value: unknown): value is types.AdditionalPropertiesAnyOf0 {
if(!_isReferenceAdditionalPropertiesAnyOf0(value)) {
return false;
}
return true;
}
function _isReferenceAdditionalPropertiesAnyOf0(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isAdditionalPropertiesAnyOf1(value: unknown): value is types.AdditionalPropertiesAnyOf1 {
if(!_isReferenceAdditionalPropertiesAnyOf1(value)) {
return false;
}
return true;
}
function _isReferenceAdditionalPropertiesAnyOf1(value: unknown): value is unknown {
if(!isStringArray(value)) {
return false;
}
return true;
}
export function isAnchorString(value: unknown): value is types.AnchorString {
if(!_isStringAnchorString(value)) {
return false;
}
return true;
}
function _isStringAnchorString(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
if(new RegExp("^[A-Za-z_][-A-Za-z0-9._]*$").test(value)) {
return false;
}
return true;
}
export function isUriReferenceString(value: unknown): value is types.UriReferenceString {
if(!_isStringUriReferenceString(value)) {
return false;
}
return true;
}
function _isStringUriReferenceString(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isCore(value: unknown): value is types.Core {
if(!_isMapCore(value) && !_isBooleanCore(value)) {
return false;
}
return true;
}
function _isMapCore(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
switch(propertyName) {
case "$id":
if(!isId(propertyValue)) {
return false;
}
break;
case "$schema":
if(!isPropertiesSchema(propertyValue)) {
return false;
}
break;
case "$ref":
if(!isRef(propertyValue)) {
return false;
}
break;
case "$anchor":
if(!isAnchor(propertyValue)) {
return false;
}
break;
case "$dynamicRef":
if(!isDynamicRef(propertyValue)) {
return false;
}
break;
case "$dynamicAnchor":
if(!isDynamicAnchor(propertyValue)) {
return false;
}
break;
case "$vocabulary":
if(!isVocabulary(propertyValue)) {
return false;
}
break;
case "$comment":
if(!isComment(propertyValue)) {
return false;
}
break;
case "$defs":
if(!isDefs(propertyValue)) {
return false;
}
break;
}
}
return true;
}
function _isBooleanCore(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isUriString(value: unknown): value is types.UriString {
if(!_isStringUriString(value)) {
return false;
}
return true;
}
function _isStringUriString(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isId(value: unknown): value is types.Id {
if(!_isStringId(value) && !_isReferenceId(value)) {
return false;
}
return true;
}
function _isStringId(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
if(new RegExp("^[^#]*#?$").test(value)) {
return false;
}
return true;
}
function _isReferenceId(value: unknown): value is unknown {
if(!isUriReferenceString(value)) {
return false;
}
return true;
}
export function isPropertiesSchema(value: unknown): value is types.PropertiesSchema {
if(!_isReferencePropertiesSchema(value)) {
return false;
}
return true;
}
function _isReferencePropertiesSchema(value: unknown): value is unknown {
if(!isUriString(value)) {
return false;
}
return true;
}
export function isRef(value: unknown): value is types.Ref {
if(!_isReferenceRef(value)) {
return false;
}
return true;
}
function _isReferenceRef(value: unknown): value is unknown {
if(!isUriReferenceString(value)) {
return false;
}
return true;
}
export function isAnchor(value: unknown): value is types.Anchor {
if(!_isReferenceAnchor(value)) {
return false;
}
return true;
}
function _isReferenceAnchor(value: unknown): value is unknown {
if(!isAnchorString(value)) {
return false;
}
return true;
}
export function isDynamicRef(value: unknown): value is types.DynamicRef {
if(!_isReferenceDynamicRef(value)) {
return false;
}
return true;
}
function _isReferenceDynamicRef(value: unknown): value is unknown {
if(!isUriReferenceString(value)) {
return false;
}
return true;
}
export function isDynamicAnchor(value: unknown): value is types.DynamicAnchor {
if(!_isReferenceDynamicAnchor(value)) {
return false;
}
return true;
}
function _isReferenceDynamicAnchor(value: unknown): value is unknown {
if(!isAnchorString(value)) {
return false;
}
return true;
}
export function isVocabulary(value: unknown): value is types.Vocabulary {
if(!_isMapVocabulary(value)) {
return false;
}
return true;
}
function _isMapVocabulary(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
if(!isVocabularyPropertyNames(propertyValue)) {
return false;
}
if(!isVocabularyAdditionalProperties(propertyValue)) {
return false;
}
}
return true;
}
export function isComment(value: unknown): value is types.Comment {
if(!_isStringComment(value)) {
return false;
}
return true;
}
function _isStringComment(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isDefs(value: unknown): value is types.Defs {
if(!_isMapDefs(value)) {
return false;
}
return true;
}
function _isMapDefs(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
if(!isDefsAdditionalProperties(propertyValue)) {
return false;
}
}
return true;
}
export function isVocabularyAdditionalProperties(value: unknown): value is types.VocabularyAdditionalProperties {
if(!_isBooleanVocabularyAdditionalProperties(value)) {
return false;
}
return true;
}
function _isBooleanVocabularyAdditionalProperties(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isVocabularyPropertyNames(value: unknown): value is types.VocabularyPropertyNames {
if(!_isReferenceVocabularyPropertyNames(value)) {
return false;
}
return true;
}
function _isReferenceVocabularyPropertyNames(value: unknown): value is unknown {
if(!isUriString(value)) {
return false;
}
return true;
}
export function isDefsAdditionalProperties(value: unknown): value is types.DefsAdditionalProperties {
if(!_isReferenceDefsAdditionalProperties(value)) {
return false;
}
return true;
}
function _isReferenceDefsAdditionalProperties(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isApplicator(value: unknown): value is types.Applicator {
if(!_isMapApplicator(value) && !_isBooleanApplicator(value)) {
return false;
}
return true;
}
function _isMapApplicator(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
switch(propertyName) {
case "prefixItems":
if(!isPrefixItems(propertyValue)) {
return false;
}
break;
case "items":
if(!isPropertiesItems(propertyValue)) {
return false;
}
break;
case "contains":
if(!isContains(propertyValue)) {
return false;
}
break;
case "additionalProperties":
if(!isApplicatorPropertiesAdditionalProperties(propertyValue)) {
return false;
}
break;
case "properties":
if(!isProperties(propertyValue)) {
return false;
}
break;
case "patternProperties":
if(!isPatternProperties(propertyValue)) {
return false;
}
break;
case "dependentSchemas":
if(!isDependentSchemas(propertyValue)) {
return false;
}
break;
case "propertyNames":
if(!isPropertiesPropertyNames(propertyValue)) {
return false;
}
break;
case "if":
if(!isIf(propertyValue)) {
return false;
}
break;
case "then":
if(!isThen(propertyValue)) {
return false;
}
break;
case "else":
if(!isElse(propertyValue)) {
return false;
}
break;
case "allOf":
if(!isAllOf(propertyValue)) {
return false;
}
break;
case "anyOf":
if(!isAnyOf(propertyValue)) {
return false;
}
break;
case "oneOf":
if(!isOneOf(propertyValue)) {
return false;
}
break;
case "not":
if(!isNot(propertyValue)) {
return false;
}
break;
}
}
return true;
}
function _isBooleanApplicator(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isSchemaArray(value: unknown): value is types.SchemaArray {
if(!_isArraySchemaArray(value)) {
return false;
}
return true;
}
function _isArraySchemaArray(value: unknown): value is unknown {
if(!Array.isArray(value)) {
return false;
}
if(value.length < 1) {
return false;
}
for(let elementIndex = 0; elementIndex < value.length; elementIndex ++) {
const elementValue = value[elementIndex];
if(!isSchemaArrayItems(elementValue)) {
return false;
}
}
return true;
}
export function isPrefixItems(value: unknown): value is types.PrefixItems {
if(!_isReferencePrefixItems(value)) {
return false;
}
return true;
}
function _isReferencePrefixItems(value: unknown): value is unknown {
if(!isSchemaArray(value)) {
return false;
}
return true;
}
export function isPropertiesItems(value: unknown): value is types.PropertiesItems {
if(!_isReferencePropertiesItems(value)) {
return false;
}
return true;
}
function _isReferencePropertiesItems(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isContains(value: unknown): value is types.Contains {
if(!_isReferenceContains(value)) {
return false;
}
return true;
}
function _isReferenceContains(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isApplicatorPropertiesAdditionalProperties(value: unknown): value is types.ApplicatorPropertiesAdditionalProperties {
if(!_isReferenceApplicatorPropertiesAdditionalProperties(value)) {
return false;
}
return true;
}
function _isReferenceApplicatorPropertiesAdditionalProperties(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isProperties(value: unknown): value is types.Properties {
if(!_isMapProperties(value)) {
return false;
}
return true;
}
function _isMapProperties(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
if(!isPropertiesPropertiesAdditionalProperties(propertyValue)) {
return false;
}
}
return true;
}
export function isPatternProperties(value: unknown): value is types.PatternProperties {
if(!_isMapPatternProperties(value)) {
return false;
}
return true;
}
function _isMapPatternProperties(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
if(!isPatternPropertiesPropertyNames(propertyValue)) {
return false;
}
if(!isPatternPropertiesAdditionalProperties(propertyValue)) {
return false;
}
}
return true;
}
export function isDependentSchemas(value: unknown): value is types.DependentSchemas {
if(!_isMapDependentSchemas(value)) {
return false;
}
return true;
}
function _isMapDependentSchemas(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
if(!isDependentSchemasAdditionalProperties(propertyValue)) {
return false;
}
}
return true;
}
export function isPropertiesPropertyNames(value: unknown): value is types.PropertiesPropertyNames {
if(!_isReferencePropertiesPropertyNames(value)) {
return false;
}
return true;
}
function _isReferencePropertiesPropertyNames(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isIf(value: unknown): value is types.If {
if(!_isReferenceIf(value)) {
return false;
}
return true;
}
function _isReferenceIf(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isThen(value: unknown): value is types.Then {
if(!_isReferenceThen(value)) {
return false;
}
return true;
}
function _isReferenceThen(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isElse(value: unknown): value is types.Else {
if(!_isReferenceElse(value)) {
return false;
}
return true;
}
function _isReferenceElse(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isAllOf(value: unknown): value is types.AllOf {
if(!_isReferenceAllOf(value)) {
return false;
}
return true;
}
function _isReferenceAllOf(value: unknown): value is unknown {
if(!isSchemaArray(value)) {
return false;
}
return true;
}
export function isAnyOf(value: unknown): value is types.AnyOf {
if(!_isReferenceAnyOf(value)) {
return false;
}
return true;
}
function _isReferenceAnyOf(value: unknown): value is unknown {
if(!isSchemaArray(value)) {
return false;
}
return true;
}
export function isOneOf(value: unknown): value is types.OneOf {
if(!_isReferenceOneOf(value)) {
return false;
}
return true;
}
function _isReferenceOneOf(value: unknown): value is unknown {
if(!isSchemaArray(value)) {
return false;
}
return true;
}
export function isNot(value: unknown): value is types.Not {
if(!_isReferenceNot(value)) {
return false;
}
return true;
}
function _isReferenceNot(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isSchemaArrayItems(value: unknown): value is types.SchemaArrayItems {
if(!_isReferenceSchemaArrayItems(value)) {
return false;
}
return true;
}
function _isReferenceSchemaArrayItems(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isPropertiesPropertiesAdditionalProperties(value: unknown): value is types.PropertiesPropertiesAdditionalProperties {
if(!_isReferencePropertiesPropertiesAdditionalProperties(value)) {
return false;
}
return true;
}
function _isReferencePropertiesPropertiesAdditionalProperties(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isPatternPropertiesAdditionalProperties(value: unknown): value is types.PatternPropertiesAdditionalProperties {
if(!_isReferencePatternPropertiesAdditionalProperties(value)) {
return false;
}
return true;
}
function _isReferencePatternPropertiesAdditionalProperties(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isPatternPropertiesPropertyNames(value: unknown): value is types.PatternPropertiesPropertyNames {
if(!_isStringPatternPropertiesPropertyNames(value)) {
return false;
}
return true;
}
function _isStringPatternPropertiesPropertyNames(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isDependentSchemasAdditionalProperties(value: unknown): value is types.DependentSchemasAdditionalProperties {
if(!_isReferenceDependentSchemasAdditionalProperties(value)) {
return false;
}
return true;
}
function _isReferenceDependentSchemasAdditionalProperties(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isUnevaluated(value: unknown): value is types.Unevaluated {
if(!_isMapUnevaluated(value) && !_isBooleanUnevaluated(value)) {
return false;
}
return true;
}
function _isMapUnevaluated(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
switch(propertyName) {
case "unevaluatedItems":
if(!isUnevaluatedItems(propertyValue)) {
return false;
}
break;
case "unevaluatedProperties":
if(!isUnevaluatedProperties(propertyValue)) {
return false;
}
break;
}
}
return true;
}
function _isBooleanUnevaluated(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isUnevaluatedItems(value: unknown): value is types.UnevaluatedItems {
if(!_isReferenceUnevaluatedItems(value)) {
return false;
}
return true;
}
function _isReferenceUnevaluatedItems(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isUnevaluatedProperties(value: unknown): value is types.UnevaluatedProperties {
if(!_isReferenceUnevaluatedProperties(value)) {
return false;
}
return true;
}
function _isReferenceUnevaluatedProperties(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
export function isValidation(value: unknown): value is types.Validation {
if(!_isMapValidation(value) && !_isBooleanValidation(value)) {
return false;
}
return true;
}
function _isMapValidation(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
switch(propertyName) {
case "type":
if(!isType(propertyValue)) {
return false;
}
break;
case "const":
if(!isConst(propertyValue)) {
return false;
}
break;
case "enum":
if(!isEnum(propertyValue)) {
return false;
}
break;
case "multipleOf":
if(!isMultipleOf(propertyValue)) {
return false;
}
break;
case "maximum":
if(!isMaximum(propertyValue)) {
return false;
}
break;
case "exclusiveMaximum":
if(!isExclusiveMaximum(propertyValue)) {
return false;
}
break;
case "minimum":
if(!isMinimum(propertyValue)) {
return false;
}
break;
case "exclusiveMinimum":
if(!isExclusiveMinimum(propertyValue)) {
return false;
}
break;
case "maxLength":
if(!isMaxLength(propertyValue)) {
return false;
}
break;
case "minLength":
if(!isMinLength(propertyValue)) {
return false;
}
break;
case "pattern":
if(!isPattern(propertyValue)) {
return false;
}
break;
case "maxItems":
if(!isMaxItems(propertyValue)) {
return false;
}
break;
case "minItems":
if(!isMinItems(propertyValue)) {
return false;
}
break;
case "uniqueItems":
if(!isUniqueItems(propertyValue)) {
return false;
}
break;
case "maxContains":
if(!isMaxContains(propertyValue)) {
return false;
}
break;
case "minContains":
if(!isMinContains(propertyValue)) {
return false;
}
break;
case "maxProperties":
if(!isMaxProperties(propertyValue)) {
return false;
}
break;
case "minProperties":
if(!isMinProperties(propertyValue)) {
return false;
}
break;
case "required":
if(!isRequired(propertyValue)) {
return false;
}
break;
case "dependentRequired":
if(!isDependentRequired(propertyValue)) {
return false;
}
break;
}
}
return true;
}
function _isBooleanValidation(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isNonNegativeInteger(value: unknown): value is types.NonNegativeInteger {
if(!_isIntegerNonNegativeInteger(value)) {
return false;
}
return true;
}
function _isIntegerNonNegativeInteger(value: unknown): value is unknown {
if(typeof value !== "number" || isNaN(value)) {
return false;
}
if(value < 0) {
return false;
}
return true;
}
export function isNonNegativeIntegerDefault0(value: unknown): value is types.NonNegativeIntegerDefault0 {
if(!_isReferenceNonNegativeIntegerDefault0(value)) {
return false;
}
return true;
}
function _isReferenceNonNegativeIntegerDefault0(value: unknown): value is unknown {
if(!isNonNegativeInteger(value)) {
return false;
}
return true;
}
export function isSimpleTypes(value: unknown): value is types.SimpleTypes {
if(!_isStringSimpleTypes(value)) {
return false;
}
return true;
}
function _isStringSimpleTypes(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
if(value !== "array" && value !== "boolean" && value !== "integer" && value !== "null" && value !== "number" && value !== "object" && value !== "string") {
return false;
}
return true;
}
export function isStringArray(value: unknown): value is types.StringArray {
if(!_isArrayStringArray(value)) {
return false;
}
return true;
}
function _isArrayStringArray(value: unknown): value is unknown {
if(!Array.isArray(value)) {
return false;
}
const elementValueSeen = new Set<unknown>();
for(let elementIndex = 0; elementIndex < value.length; elementIndex ++) {
const elementValue = value[elementIndex];
if(elementValueSeen.has(elementValue)) {
return false;
}
elementValueSeen.add(elementValue);
if(!isStringArrayItems(elementValue)) {
return false;
}
}
return true;
}
export function isType(value: unknown): value is types.Type {
if(!_isAnyOfType(value)) {
return false;
}
return true;
}
function _isAnyOfType(value: unknown): value is unknown {
if(isTypeAnyOf0(value)) {
return true;
}
if(isTypeAnyOf1(value)) {
return true;
}
return false;
}
export function isConst(value: unknown): value is types.Const {
if(!_isAnyConst(value)) {
return false;
}
return true;
}
function _isAnyConst(value: unknown): value is unknown {
return true;
}
export function isEnum(value: unknown): value is types.Enum {
if(!_isArrayEnum(value)) {
return false;
}
return true;
}
function _isArrayEnum(value: unknown): value is unknown {
if(!Array.isArray(value)) {
return false;
}
for(let elementIndex = 0; elementIndex < value.length; elementIndex ++) {
const elementValue = value[elementIndex];
if(!isEnumItems(elementValue)) {
return false;
}
}
return true;
}
export function isMultipleOf(value: unknown): value is types.MultipleOf {
if(!_isNumberMultipleOf(value)) {
return false;
}
return true;
}
function _isNumberMultipleOf(value: unknown): value is unknown {
if(typeof value !== "number" || isNaN(value) || value % 1 !== 0) {
return false;
}
if(value <= 0) {
return false;
}
return true;
}
export function isMaximum(value: unknown): value is types.Maximum {
if(!_isNumberMaximum(value)) {
return false;
}
return true;
}
function _isNumberMaximum(value: unknown): value is unknown {
if(typeof value !== "number" || isNaN(value) || value % 1 !== 0) {
return false;
}
return true;
}
export function isExclusiveMaximum(value: unknown): value is types.ExclusiveMaximum {
if(!_isNumberExclusiveMaximum(value)) {
return false;
}
return true;
}
function _isNumberExclusiveMaximum(value: unknown): value is unknown {
if(typeof value !== "number" || isNaN(value) || value % 1 !== 0) {
return false;
}
return true;
}
export function isMinimum(value: unknown): value is types.Minimum {
if(!_isNumberMinimum(value)) {
return false;
}
return true;
}
function _isNumberMinimum(value: unknown): value is unknown {
if(typeof value !== "number" || isNaN(value) || value % 1 !== 0) {
return false;
}
return true;
}
export function isExclusiveMinimum(value: unknown): value is types.ExclusiveMinimum {
if(!_isNumberExclusiveMinimum(value)) {
return false;
}
return true;
}
function _isNumberExclusiveMinimum(value: unknown): value is unknown {
if(typeof value !== "number" || isNaN(value) || value % 1 !== 0) {
return false;
}
return true;
}
export function isMaxLength(value: unknown): value is types.MaxLength {
if(!_isReferenceMaxLength(value)) {
return false;
}
return true;
}
function _isReferenceMaxLength(value: unknown): value is unknown {
if(!isNonNegativeInteger(value)) {
return false;
}
return true;
}
export function isMinLength(value: unknown): value is types.MinLength {
if(!_isReferenceMinLength(value)) {
return false;
}
return true;
}
function _isReferenceMinLength(value: unknown): value is unknown {
if(!isNonNegativeIntegerDefault0(value)) {
return false;
}
return true;
}
export function isPattern(value: unknown): value is types.Pattern {
if(!_isStringPattern(value)) {
return false;
}
return true;
}
function _isStringPattern(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isMaxItems(value: unknown): value is types.MaxItems {
if(!_isReferenceMaxItems(value)) {
return false;
}
return true;
}
function _isReferenceMaxItems(value: unknown): value is unknown {
if(!isNonNegativeInteger(value)) {
return false;
}
return true;
}
export function isMinItems(value: unknown): value is types.MinItems {
if(!_isReferenceMinItems(value)) {
return false;
}
return true;
}
function _isReferenceMinItems(value: unknown): value is unknown {
if(!isNonNegativeIntegerDefault0(value)) {
return false;
}
return true;
}
export function isUniqueItems(value: unknown): value is types.UniqueItems {
if(!_isBooleanUniqueItems(value)) {
return false;
}
return true;
}
function _isBooleanUniqueItems(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isMaxContains(value: unknown): value is types.MaxContains {
if(!_isReferenceMaxContains(value)) {
return false;
}
return true;
}
function _isReferenceMaxContains(value: unknown): value is unknown {
if(!isNonNegativeInteger(value)) {
return false;
}
return true;
}
export function isMinContains(value: unknown): value is types.MinContains {
if(!_isReferenceMinContains(value)) {
return false;
}
return true;
}
function _isReferenceMinContains(value: unknown): value is unknown {
if(!isNonNegativeInteger(value)) {
return false;
}
return true;
}
export function isMaxProperties(value: unknown): value is types.MaxProperties {
if(!_isReferenceMaxProperties(value)) {
return false;
}
return true;
}
function _isReferenceMaxProperties(value: unknown): value is unknown {
if(!isNonNegativeInteger(value)) {
return false;
}
return true;
}
export function isMinProperties(value: unknown): value is types.MinProperties {
if(!_isReferenceMinProperties(value)) {
return false;
}
return true;
}
function _isReferenceMinProperties(value: unknown): value is unknown {
if(!isNonNegativeIntegerDefault0(value)) {
return false;
}
return true;
}
export function isRequired(value: unknown): value is types.Required {
if(!_isReferenceRequired(value)) {
return false;
}
return true;
}
function _isReferenceRequired(value: unknown): value is unknown {
if(!isStringArray(value)) {
return false;
}
return true;
}
export function isDependentRequired(value: unknown): value is types.DependentRequired {
if(!_isMapDependentRequired(value)) {
return false;
}
return true;
}
function _isMapDependentRequired(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
if(!isDependentRequiredAdditionalProperties(propertyValue)) {
return false;
}
}
return true;
}
export function isStringArrayItems(value: unknown): value is types.StringArrayItems {
if(!_isStringStringArrayItems(value)) {
return false;
}
return true;
}
function _isStringStringArrayItems(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isTypeAnyOf0(value: unknown): value is types.TypeAnyOf0 {
if(!_isReferenceTypeAnyOf0(value)) {
return false;
}
return true;
}
function _isReferenceTypeAnyOf0(value: unknown): value is unknown {
if(!isSimpleTypes(value)) {
return false;
}
return true;
}
export function isTypeAnyOf1(value: unknown): value is types.TypeAnyOf1 {
if(!_isArrayTypeAnyOf1(value)) {
return false;
}
return true;
}
function _isArrayTypeAnyOf1(value: unknown): value is unknown {
if(!Array.isArray(value)) {
return false;
}
if(value.length < 1) {
return false;
}
const elementValueSeen = new Set<unknown>();
for(let elementIndex = 0; elementIndex < value.length; elementIndex ++) {
const elementValue = value[elementIndex];
if(elementValueSeen.has(elementValue)) {
return false;
}
elementValueSeen.add(elementValue);
if(!isAnyOf1Items(elementValue)) {
return false;
}
}
return true;
}
export function isEnumItems(value: unknown): value is types.EnumItems {
if(!_isAnyEnumItems(value)) {
return false;
}
return true;
}
function _isAnyEnumItems(value: unknown): value is unknown {
return true;
}
export function isDependentRequiredAdditionalProperties(value: unknown): value is types.DependentRequiredAdditionalProperties {
if(!_isReferenceDependentRequiredAdditionalProperties(value)) {
return false;
}
return true;
}
function _isReferenceDependentRequiredAdditionalProperties(value: unknown): value is unknown {
if(!isStringArray(value)) {
return false;
}
return true;
}
export function isAnyOf1Items(value: unknown): value is types.AnyOf1Items {
if(!_isReferenceAnyOf1Items(value)) {
return false;
}
return true;
}
function _isReferenceAnyOf1Items(value: unknown): value is unknown {
if(!isSimpleTypes(value)) {
return false;
}
return true;
}
export function isMetaData(value: unknown): value is types.MetaData {
if(!_isMapMetaData(value) && !_isBooleanMetaData(value)) {
return false;
}
return true;
}
function _isMapMetaData(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
switch(propertyName) {
case "title":
if(!isTitle(propertyValue)) {
return false;
}
break;
case "description":
if(!isDescription(propertyValue)) {
return false;
}
break;
case "default":
if(!isDefault(propertyValue)) {
return false;
}
break;
case "deprecated":
if(!isDeprecated(propertyValue)) {
return false;
}
break;
case "readOnly":
if(!isReadOnly(propertyValue)) {
return false;
}
break;
case "writeOnly":
if(!isWriteOnly(propertyValue)) {
return false;
}
break;
case "examples":
if(!isExamples(propertyValue)) {
return false;
}
break;
}
}
return true;
}
function _isBooleanMetaData(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isTitle(value: unknown): value is types.Title {
if(!_isStringTitle(value)) {
return false;
}
return true;
}
function _isStringTitle(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isDescription(value: unknown): value is types.Description {
if(!_isStringDescription(value)) {
return false;
}
return true;
}
function _isStringDescription(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isDefault(value: unknown): value is types.Default {
if(!_isAnyDefault(value)) {
return false;
}
return true;
}
function _isAnyDefault(value: unknown): value is unknown {
return true;
}
export function isDeprecated(value: unknown): value is types.Deprecated {
if(!_isBooleanDeprecated(value)) {
return false;
}
return true;
}
function _isBooleanDeprecated(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isReadOnly(value: unknown): value is types.ReadOnly {
if(!_isBooleanReadOnly(value)) {
return false;
}
return true;
}
function _isBooleanReadOnly(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isWriteOnly(value: unknown): value is types.WriteOnly {
if(!_isBooleanWriteOnly(value)) {
return false;
}
return true;
}
function _isBooleanWriteOnly(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isExamples(value: unknown): value is types.Examples {
if(!_isArrayExamples(value)) {
return false;
}
return true;
}
function _isArrayExamples(value: unknown): value is unknown {
if(!Array.isArray(value)) {
return false;
}
for(let elementIndex = 0; elementIndex < value.length; elementIndex ++) {
const elementValue = value[elementIndex];
if(!isExamplesItems(elementValue)) {
return false;
}
}
return true;
}
export function isExamplesItems(value: unknown): value is types.ExamplesItems {
if(!_isAnyExamplesItems(value)) {
return false;
}
return true;
}
function _isAnyExamplesItems(value: unknown): value is unknown {
return true;
}
export function isFormatAnnotation(value: unknown): value is types.FormatAnnotation {
if(!_isMapFormatAnnotation(value) && !_isBooleanFormatAnnotation(value)) {
return false;
}
return true;
}
function _isMapFormatAnnotation(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
switch(propertyName) {
case "format":
if(!isFormat(propertyValue)) {
return false;
}
break;
}
}
return true;
}
function _isBooleanFormatAnnotation(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isFormat(value: unknown): value is types.Format {
if(!_isStringFormat(value)) {
return false;
}
return true;
}
function _isStringFormat(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isContent(value: unknown): value is types.Content {
if(!_isMapContent(value) && !_isBooleanContent(value)) {
return false;
}
return true;
}
function _isMapContent(value: unknown): value is unknown {
if(typeof value !== "object" || value === null || Array.isArray(value)) {
return false;
}
for(const propertyName in value) {
const propertyValue = value[propertyName as keyof typeof value];
switch(propertyName) {
case "contentEncoding":
if(!isContentEncoding(propertyValue)) {
return false;
}
break;
case "contentMediaType":
if(!isContentMediaType(propertyValue)) {
return false;
}
break;
case "contentSchema":
if(!isContentSchema(propertyValue)) {
return false;
}
break;
}
}
return true;
}
function _isBooleanContent(value: unknown): value is unknown {
if(typeof value !== "boolean") {
return false;
}
return true;
}
export function isContentEncoding(value: unknown): value is types.ContentEncoding {
if(!_isStringContentEncoding(value)) {
return false;
}
return true;
}
function _isStringContentEncoding(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isContentMediaType(value: unknown): value is types.ContentMediaType {
if(!_isStringContentMediaType(value)) {
return false;
}
return true;
}
function _isStringContentMediaType(value: unknown): value is unknown {
if(typeof value !== "string") {
return false;
}
return true;
}
export function isContentSchema(value: unknown): value is types.ContentSchema {
if(!_isReferenceContentSchema(value)) {
return false;
}
return true;
}
function _isReferenceContentSchema(value: unknown): value is unknown {
if(!isDraft202012Schema(value)) {
return false;
}
return true;
}
