version: "0.2"
words:
  - automagically
  - Bulthuis
  - camelcase
  - clippy
  - Deque
  - endregion
  - esbenp
  - Hasher
  - Inflector
  - lcov
  - luvdasun
  - notdir
  - presolved
  - reqwest
  - ryanluker
  - serde
  - snakecase
  - structs
  - tamasfe
  - unalias
  - urlencoding
  - vadimcn
useGitignore: true
files:
  - "**"
enableFiletypes:
  - "*"
