#!/bin/sh

set -e

cd $(dirname $0)

export NODE_ENV=development

set +e

ERROR=0

for F in $(ls fixtures/specifications); do
  echo $F

  if ! cargo run --package jns42-generator package \
    fixtures/specifications/$F \
    --package-directory .package/package/cargo \
    --package-name $(basename $F) \
    --package-version "0.0.0" \
  ; then 
    ERROR=1;
  fi;

done;

exit $ERROR


