#!/bin/sh

set -e

cd $(dirname $0)

export NODE_ENV=development

npm run build --workspaces --if-present

set +e

ERROR=0

for F in $(ls fixtures/specifications); do
  echo $F

  if ! node ./packages/npm/jns42-generator/bundled/program.js package \
    fixtures/specifications/$F \
    --package-directory .package/package/npm \
    --package-name $(basename $F) \
    --package-version "0.0.0" \
  ; then 
    ERROR=1;
  fi;

done;

exit $ERROR


