#!/bin/sh

set -e

cd $(dirname $0)

export NODE_ENV=development

npm run build --workspaces --if-present
npm install --no-package-lock

set +e

ERROR=0

for F in $(ls fixtures/testing/*.yaml); do
  echo $(basename $F .yaml)

  if ! npx jns42-generator test \
    $F \
    --package-directory .package/test \
    --package-name $(basename $F .yaml) \
    --package-version "0.0.0" \
  ; then 
    ERROR=1;
  fi;

done;

exit $ERROR


