#!/bin/sh

set -e

cd $(dirname $0)

export NODE_ENV=development

npm run build --workspaces --if-present

set +e

ERROR=0

for F in $(ls fixtures/testing/*); do
  echo $F

if ! ./packages/npm/jns42-generator/bundled/program.js package \
      $F \
    --package-directory .package/test/npm \
    --package-name $(basename $F .yaml) \
    --package-version "0.0.0" \
  ; then 
    ERROR=1;
  fi;

done;

exit $ERROR


