#!/bin/sh

set -e

cd $(dirname $0)

export NODE_ENV=development

npm run build --workspaces --if-present

set +e

ERROR=0

export DIRECTORY=/tmp/jns42/$RANDOM

for F in $(ls fixtures/testing); do
  export N=${F%.*};
  echo $N;

  if ! node ./packages/npm/jns42-generator/bundled/program.js test \
    fixtures/testing/$F \
    --package-directory $DIRECTORY/$N \
    --package-name $N \
    --package-version "0.0.0" \
  ; then 
    ERROR=1;
  fi;

done;

rm -rf $DIRECTORY

exit $ERROR


