export enum SchemaTransform {
  Explode = 10,
  FlattenAllOf = 21,
  FlattenAnyOf = 22,
  FlattenOneOf = 23,
  FlipAllOfAnyOf = 33,
  FlipAllOfOneOf = 34,
  FlipAnyOfAllOf = 35,
  FlipAnyOfOneOf = 36,
  FlipOneOfAllOf = 37,
  FlipOneOfAnyOf = 38,
  InheritAllOf = 41,
  InheritAnyOf = 42,
  InheritOneOf = 43,
  Primary = 50,
  ResolveAllOf = 60,
  ResolveIfThenElse = 70,
  ResolveNot = 80,
  ResolveSingleAllOf = 91,
  ResolveSingleAnyOf = 92,
  ResolveSingleOneOf = 93,
  SingleType = 100,
}
