export enum SchemaTransform {
  explode = 10,
  flattenAllOf = 21,
  flattenAnyOf = 22,
  flattenOneOf = 23,
  flipAllOfAnyOf = 31,
  flipAllOfOneOf = 32,
  flipAnyOfAllOf = 33,
  flipAnyOfOneOf = 34,
  flipOneOfAllOf = 35,
  flipOneOfAnyOf = 36,
  inheritAllOf = 41,
  inheritAnyOf = 42,
  inheritOneOf = 43,
  primary = 50,
  resolveAllOf = 60,
  resolveIfThenElse = 70,
  resolveNot = 80,
  resolveSingleAllOf = 91,
  resolveSingleAnyOf = 92,
  resolveSingleOneOf = 93,
  singleType = 100,
}
