import { NestedText, flattenNestedText } from "./iterable-text-template.js";

export function formatData(content: unknown) {
  return JSON.stringify(content, undefined, 2);
}

export function formatStatements(nestedCode: NestedText) {
  const banner = `
// @generated by
//     __             _____     _                 ___ ___ 
//  _ |  |___ ___ ___|   __|___| |_ ___ _____  __| | |_  |
// | |_| |_ -| . |   |__   |  _|   | -_|     ||. |_  |  _|
// |_____|___|___|_|_|_____|___|_|_|___|_|_|_|___| |_|___|
//                                 -- www.JsonSchema42.org
`.trim();

  const code = [...flattenNestedText(nestedCode)].join("");

  return `${banner}\n\n${code}`;
}
