[package]
name = "jns42-tester"
version = "0.0.0"
edition = "2024"
description = "Test jns42"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.JsonSchema42.org"
keywords = []
repository = "git@github.com:LuvDaSun/JsonSchema42"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
clap = { version = "^4.1.14", features = ["derive"] }
serde = "^1.0.158"
serde_json = "^1.0.94"
serde_yaml = "^0.9.31"
toml = "^0.8.10"
jns42-core = { path = "../jns42-core" }

[[bin]]
name = "jns42-tester"
path = "src/main.rs"
