pub fn banner(prefix: &str, version: &str) -> String {
  [
    format!("{} @generated by", prefix),
    prefix.to_owned(),
    format!(
      "{}      __             _____     _                 ___ ___ ",
      prefix
    ),
    format!(
      "{}   _ |  |___ ___ ___|   __|___| |_ ___ _____  __| | |_  |",
      prefix
    ),
    format!(
      "{}  | |_| |_ -| . |   |__   |  _|   | -_|     ||. |_  |  _|",
      prefix
    ),
    format!(
      "{}  |_____|___|___|_|_|_____|___|_|_|___|_|_|_|___| |_|___|",
      prefix
    ),
    format!("{}   {:30} -- www.JsonSchema42.org", prefix, version),
  ]
  .join("\n")
}
