[package]
name = "jns42-core"
version = "0.1.0"
edition = "2021"
description = "Core of jns42"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.JsonSchema42.org"
keywords = ["json", "schema"]
repository = "git@github.com:LuvDaSun/JsonSchema42"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
im = "^15.1.0"
url = "^2.3.1"
serde = { version = "^1.0.158", features = ["derive"] }
serde_json = "^1.0.94"
once_cell = "^1.19.0"
proc-macro2 = "^1.0.78"
quote = "^1.0.35"
regex = "^1.10.3"
percent-encoding = "2.3.1"

[lib]
crate-type = ["rlib", "cdylib"]
