[package]
name = "jns42-core"
version = "0.1.1"
edition = "2021"
description = "Core of jns42"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.JsonSchema42.org"
keywords = ["json", "schema"]
repository = "https://github.com/LuvDaSun/JsonSchema42"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
im = "^15.1.0"
url = "^2.3.1"
serde = { version = "^1.0.158", features = ["derive"] }
serde_json = "^1.0.94"
once_cell = "^1.19.0"
proc-macro2 = "^1.0.78"
quote = "^1.0.35"
regex = "^1.10.3"
urlencoding = "2.1.3"
itertools = "0.12.1"
futures = { version = "0.3.30" }
serde_yaml = "^0.9.31"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
gloo = "0.11.0"
semver = "1.0.23"
tokio = { version = "1.38.0", features = ["sync"] }


[target.'cfg(not(target_os = "unknown"))'.dependencies]
surf = "2.3.2"

[lib]
crate-type = ["rlib", "cdylib"]
