// @generated by
//     __             _____     _                 ___ ___
//  _ |  |___ ___ ___|   __|___| |_ ___ _____  __| | |_  |
// | |_| |_ -| . |   |__   |  _|   | -_|     ||. |_  |  _|
// |_____|___|___|_|_|_____|___|_|_|___|_|_|_|___| |_|___|
// v0.9.6                          -- www.JsonSchema42.org
//
/**
* @summary JsonSchema42 intermediate schema
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json}
*/
export function parseSchemaDocument(value: unknown): unknown {
return (typeof value === "object" && value !== null && !Array.isArray(value)) ?
{
"$schema": parseSchema(value["$schema" as keyof typeof value]),
"schemas": parseSchemas(value["schemas" as keyof typeof value]),
} :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node}
*/
export function parseNode(value: unknown): unknown {
return (typeof value === "object" && value !== null && !Array.isArray(value)) ?
{
"title": parseTitle(value["title" as keyof typeof value]),
"description": parseDescription(value["description" as keyof typeof value]),
"examples": parseExamples(value["examples" as keyof typeof value]),
"deprecated": parseDeprecated(value["deprecated" as keyof typeof value]),
"types": parseTypes(value["types" as keyof typeof value]),
"reference": parseReference(value["reference" as keyof typeof value]),
"oneOf": parseOneOf(value["oneOf" as keyof typeof value]),
"anyOf": parseAnyOf(value["anyOf" as keyof typeof value]),
"allOf": parseAllOf(value["allOf" as keyof typeof value]),
"if": parseIf(value["if" as keyof typeof value]),
"then": parseThen(value["then" as keyof typeof value]),
"else": parseElse(value["else" as keyof typeof value]),
"not": parseNot(value["not" as keyof typeof value]),
"dependentSchemas": parseDependentSchemas(value["dependentSchemas" as keyof typeof value]),
"objectProperties": parseObjectProperties(value["objectProperties" as keyof typeof value]),
"mapProperties": parseMapProperties(value["mapProperties" as keyof typeof value]),
"patternProperties": parsePatternProperties(value["patternProperties" as keyof typeof value]),
"propertyNames": parsePropertyNames(value["propertyNames" as keyof typeof value]),
"tupleItems": parseTupleItems(value["tupleItems" as keyof typeof value]),
"arrayItems": parseArrayItems(value["arrayItems" as keyof typeof value]),
"contains": parseContains(value["contains" as keyof typeof value]),
"options": parseOptions(value["options" as keyof typeof value]),
"minimumInclusive": parseMinimumInclusive(value["minimumInclusive" as keyof typeof value]),
"minimumExclusive": parseMinimumExclusive(value["minimumExclusive" as keyof typeof value]),
"maximumInclusive": parseMaximumInclusive(value["maximumInclusive" as keyof typeof value]),
"maximumExclusive": parseMaximumExclusive(value["maximumExclusive" as keyof typeof value]),
"multipleOf": parseMultipleOf(value["multipleOf" as keyof typeof value]),
"minimumLength": parseMinimumLength(value["minimumLength" as keyof typeof value]),
"maximumLength": parseMaximumLength(value["maximumLength" as keyof typeof value]),
"valuePattern": parseValuePattern(value["valuePattern" as keyof typeof value]),
"valueFormat": parseValueFormat(value["valueFormat" as keyof typeof value]),
"minimumItems": parseMinimumItems(value["minimumItems" as keyof typeof value]),
"maximumItems": parseMaximumItems(value["maximumItems" as keyof typeof value]),
"uniqueItems": parseUniqueItems(value["uniqueItems" as keyof typeof value]),
"required": parseRequired(value["required" as keyof typeof value]),
"minimumProperties": parseMinimumProperties(value["minimumProperties" as keyof typeof value]),
"maximumProperties": parseMaximumProperties(value["maximumProperties" as keyof typeof value]),
} :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node-reference}
*/
export function parseNodeReference(value: unknown): unknown {
switch(typeof value) {
case "string":
return value;
case "number":
case "boolean":
return String(value);
default:
return undefined;
}
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/integer-value}
*/
export function parseIntegerValue(value: unknown): unknown {
switch(typeof value) {
case "string":
return Number(value);
case "number":
return value;
case "boolean":
return value ? 1 : 0;
}
return undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/number-value}
*/
export function parseNumberValue(value: unknown): unknown {
switch(typeof value) {
case "string":
return Number(value);
case "number":
return value;
case "boolean":
return value ? 1 : 0;
}
return undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/boolean-value}
*/
export function parseBooleanValue(value: unknown): unknown {
if(value == null) {
return false;
}
switch(typeof value) {
case "string":
switch(value.trim()) {
case "":
case "no":
case "off":
case "false":
case "0":
return false;
default:
return true;
}
case "number":
return Boolean(value);
case "boolean":
return value;
}
return undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/string-value}
*/
export function parseStringValue(value: unknown): unknown {
switch(typeof value) {
case "string":
return value;
case "number":
case "boolean":
return String(value);
default:
return undefined;
}
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/non-empty-string-value}
*/
export function parseNonEmptyStringValue(value: unknown): unknown {
switch(typeof value) {
case "string":
return value;
case "number":
case "boolean":
return String(value);
default:
return undefined;
}
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/amount}
*/
export function parseAmount(value: unknown): unknown {
switch(typeof value) {
case "string":
return Number(value);
case "number":
return value;
case "boolean":
return value ? 1 : 0;
}
return undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/properties/$schema}
*/
export function parseSchema(value: unknown): unknown {
switch(typeof value) {
case "string":
return value;
case "number":
case "boolean":
return String(value);
default:
return undefined;
}
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/properties/schemas}
*/
export function parseSchemas(value: unknown): unknown {
return (typeof value === "object" && value !== null && !Array.isArray(value)) ?
Object.fromEntries(
Object.entries(value).map(([name, value]) => [
((value: unknown) => {
switch(typeof value) {
case "string":
return value;
case "number":
case "boolean":
return String(value);
default:
return undefined;
}
})(name),
parseSchemasAdditionalProperties(value),
])
) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/title}
*/
export function parseTitle(value: unknown): unknown {
return parseNonEmptyStringValue(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/description}
*/
export function parseDescription(value: unknown): unknown {
return parseNonEmptyStringValue(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/examples}
*/
export function parseExamples(value: unknown): unknown {
return Array.isArray(value) ?
value.map(value => parseExamplesItems(value)) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/deprecated}
*/
export function parseDeprecated(value: unknown): unknown {
return parseBooleanValue(value);
}
/**
* @description What types does this schema describe<br />
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/types}
*/
export function parseTypes(value: unknown): unknown {
return Array.isArray(value) ?
value.map(value => parseTypesItems(value)) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/reference}
*/
export function parseReference(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/oneOf}
*/
export function parseOneOf(value: unknown): unknown {
return Array.isArray(value) ?
value.map(value => parseOneOfItems(value)) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/anyOf}
*/
export function parseAnyOf(value: unknown): unknown {
return Array.isArray(value) ?
value.map(value => parseAnyOfItems(value)) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/allOf}
*/
export function parseAllOf(value: unknown): unknown {
return Array.isArray(value) ?
value.map(value => parseAllOfItems(value)) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/if}
*/
export function parseIf(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/then}
*/
export function parseThen(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/else}
*/
export function parseElse(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/not}
*/
export function parseNot(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/dependentSchemas}
*/
export function parseDependentSchemas(value: unknown): unknown {
return (typeof value === "object" && value !== null && !Array.isArray(value)) ?
Object.fromEntries(
Object.entries(value).map(([name, value]) => [
((value: unknown) => {
switch(typeof value) {
case "string":
return value;
case "number":
case "boolean":
return String(value);
default:
return undefined;
}
})(name),
parseDependentSchemasAdditionalProperties(value),
])
) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/objectProperties}
*/
export function parseObjectProperties(value: unknown): unknown {
return (typeof value === "object" && value !== null && !Array.isArray(value)) ?
Object.fromEntries(
Object.entries(value).map(([name, value]) => [
((value: unknown) => {
switch(typeof value) {
case "string":
return value;
case "number":
case "boolean":
return String(value);
default:
return undefined;
}
})(name),
parseObjectPropertiesAdditionalProperties(value),
])
) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/mapProperties}
*/
export function parseMapProperties(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/patternProperties}
*/
export function parsePatternProperties(value: unknown): unknown {
return (typeof value === "object" && value !== null && !Array.isArray(value)) ?
Object.fromEntries(
Object.entries(value).map(([name, value]) => [
((value: unknown) => {
switch(typeof value) {
case "string":
return value;
case "number":
case "boolean":
return String(value);
default:
return undefined;
}
})(name),
parsePatternPropertiesAdditionalProperties(value),
])
) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/propertyNames}
*/
export function parsePropertyNames(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/tupleItems}
*/
export function parseTupleItems(value: unknown): unknown {
return Array.isArray(value) ?
value.map(value => parseTupleItemsItems(value)) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/arrayItems}
*/
export function parseArrayItems(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/contains}
*/
export function parseContains(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/options}
*/
export function parseOptions(value: unknown): unknown {
return Array.isArray(value) ?
value.map(value => parseOptionsItems(value)) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/minimumInclusive}
*/
export function parseMinimumInclusive(value: unknown): unknown {
return parseNumberValue(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/minimumExclusive}
*/
export function parseMinimumExclusive(value: unknown): unknown {
return parseNumberValue(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/maximumInclusive}
*/
export function parseMaximumInclusive(value: unknown): unknown {
return parseNumberValue(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/maximumExclusive}
*/
export function parseMaximumExclusive(value: unknown): unknown {
return parseNumberValue(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/multipleOf}
*/
export function parseMultipleOf(value: unknown): unknown {
return parseNumberValue(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/minimumLength}
*/
export function parseMinimumLength(value: unknown): unknown {
return parseAmount(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/maximumLength}
*/
export function parseMaximumLength(value: unknown): unknown {
return parseAmount(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/valuePattern}
*/
export function parseValuePattern(value: unknown): unknown {
return parseNonEmptyStringValue(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/valueFormat}
*/
export function parseValueFormat(value: unknown): unknown {
return parseNonEmptyStringValue(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/minimumItems}
*/
export function parseMinimumItems(value: unknown): unknown {
return parseAmount(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/maximumItems}
*/
export function parseMaximumItems(value: unknown): unknown {
return parseAmount(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/uniqueItems}
*/
export function parseUniqueItems(value: unknown): unknown {
if(value == null) {
return false;
}
switch(typeof value) {
case "string":
switch(value.trim()) {
case "":
case "no":
case "off":
case "false":
case "0":
return false;
default:
return true;
}
case "number":
return Boolean(value);
case "boolean":
return value;
}
return undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/required}
*/
export function parseRequired(value: unknown): unknown {
return Array.isArray(value) ?
value.map(value => parseRequiredItems(value)) :
undefined;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/minimumProperties}
*/
export function parseMinimumProperties(value: unknown): unknown {
return parseAmount(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/maximumProperties}
*/
export function parseMaximumProperties(value: unknown): unknown {
return parseAmount(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/properties/schemas/additionalProperties}
*/
export function parseSchemasAdditionalProperties(value: unknown): unknown {
return parseNode(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/examples/items}
*/
export function parseExamplesItems(value: unknown): unknown {
return value;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/types/items}
*/
export function parseTypesItems(value: unknown): unknown {
switch(typeof value) {
case "string":
return value;
case "number":
case "boolean":
return String(value);
default:
return undefined;
}
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/oneOf/items}
*/
export function parseOneOfItems(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/anyOf/items}
*/
export function parseAnyOfItems(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/allOf/items}
*/
export function parseAllOfItems(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/dependentSchemas/additionalProperties}
*/
export function parseDependentSchemasAdditionalProperties(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/objectProperties/additionalProperties}
*/
export function parseObjectPropertiesAdditionalProperties(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/patternProperties/additionalProperties}
*/
export function parsePatternPropertiesAdditionalProperties(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/tupleItems/items}
*/
export function parseTupleItemsItems(value: unknown): unknown {
return parseNodeReference(value);
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/options/items}
*/
export function parseOptionsItems(value: unknown): unknown {
return value;
}
/**
* @see {@link https://schema.jsonschema42.org/jns42-intermediate/schema.json#/$defs/node/properties/required/items}
*/
export function parseRequiredItems(value: unknown): unknown {
return parseStringValue(value);
}
