[package]
name = "jns42-generator"
version = "0.0.0"
edition = "2024"
description = "Generate structs and validators from json schema"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.JsonSchema42.org"
keywords = ["json", "schema", "generator"]
repository = "git@github.com:LuvDaSun/JsonSchema42"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
clap = { version = "^4.1.14", features = ["derive"] }
futures-util = "^0.3.30"
http-body-util = "^0.1.0"
hyper = { version = "^1.1.0", features = ["full"] }
hyper-util = { version = "^0.1.3", features = ["full"] }
im = "^15.1.0"
once_cell = "^1.19.0"
proc-macro2 = "^1.0.78"
quote = "^1.0.35"
regex = "^1.10.3"
reqwest = { version = "^0.11.24", features = ["stream"] }
rust-format = { version = "^0.3.4", features = ["token_stream"] }
serde = "^1.0.158"
serde_json = "^1.0.94"
serde_yaml = "^0.9.31"
tokio = { version = "^1.36.0", features = ["full"] }
toml = "^0.8.10"
url = "^2.3.1"
urlencoding = "^2.1.2"
jns42-core = { path = "../jns42-core" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "jns42-generator"
path = "src/main.rs"
