[package]
name = "jns42-generator"
version = "0.0.0"
edition = "2021"
description = "Generate structs and validators from json schema"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.JsonSchema42.org"
keywords = ["json", "schema", "generator"]
repository = "git@github.com:LuvDaSun/jns42-generator-ts"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
async-recursion = "1.0.5"
clap = { version = "~4.1.14", features = ["derive"] }
futures-util = "~0.3.30"
http-body-util = "~0.1.0"
hyper = { version = "~1.1.0", features = ["full"] }
hyper-util = { version = "~0.1.3", features = ["full"] }
reqwest = { version = "~0.11.24", features = ["stream"] }
serde = "~1.0.158"
serde_json = "~1.0.94"
serde_yaml = "~0.9.31"
tokio = { version = "~1.36.0", features = ["full"] }
url = "~2.3.1"
urlencoding = "~2.1.2"

[lib]
path = "src/lib.rs"

[[bin]]
name = "jns42_generator"
path = "src/main.rs"
