on:
  workflow_call:
    inputs:
      NPM_CONFIG_WORKSPACE:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

env:
  NPM_CONFIG_WORKSPACE: ${{ inputs.NPM_CONFIG_WORKSPACE }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  npm:
    runs-on: ubuntu-latest
    container: node:20.9-alpine3.17
    steps:
      - uses: actions/checkout@v3
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/.npmrc
      - run: npm ci
      - run: npm run build
      - run: npm version $(echo ${GITHUB_REF_NAME} | perl -pe "s/^(.*?)@(.*)$/\2/"))
      - run: npm publish --access public
