on:
  pull_request: {}
  push:
    branches:
      - "*"

jobs:
  setup-matrix:
    strategy:
      matrix:
        node-version: [21.5.0]
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces run build
      - run: make
      - run: npm run test --workspaces
