on:
  pull_request: {}
  push:
    branches:
      - "*"

jobs:
  formatting-prettier:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run formatting

  formatting-rustfmt:
    runs-on: ubuntu-latest
    container: rust:1.73.0
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - run: cargo fmt --check

  spelling:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run spelling
