on:
  pull_request: {}

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --workspace-root
      - run: npm run formatting

  spelling:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --workspace-root
      - run: npm run spelling
