on:
  pull_request: {}
  push:
    branches:
      - "*"
    paths:
      - "*"
      - .github/**
      - packages/**

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run formatting

  spelling:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run spelling

  audit:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm --workspaces audit --audit-level high

  clippy:
    runs-on: ubuntu-latest
    container: rust:1.73.0-alpine3.18
    steps:
      - uses: actions/checkout@v3
      - run: apk add build-base pkgconfig openssl-dev
      - run: rustup component add clippy
      - run: cargo clippy --all-targets
