on:
  pull_request:
    paths:
      - package-lock.json
      - .github/**
      - fixtures/**
      - packages/npm/**

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   container: node:21.5.0-alpine3.19
  #   steps:
  #     - run: corepack enable
  #     - uses: actions/checkout@v4
  #     - run: npm ci
  #     - run: npm run build --workspaces
  #     - run: npm --workspaces test

  audit:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces audit --audit-level high
