on:
  pull_request: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces audit --audit-level high

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
      - uses: extractions/setup-just@v2
      - run: corepack enable
      - run: rustup default 1.87.0

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install --force wasm-bindgen-cli@0.2.100

      - run: npm ci

      - run: just build-all
      - run: npm --workspaces test --if-present
