on:
  pull_request:
    paths:
      - package-lock.json
      - .github/**
      - fixtures/**
      - packages/npm/**

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - run: corepack enable
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build --workspaces
      - run: npm --workspaces test

  test-lts:
    strategy:
      matrix:
        node-version: [18, 20]
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build --workspaces
      - run: npm install --no-package-lock
      # node test runner seems to support globs since v21
      - if: ${{ matrix.node-version >= 21 }}
        run: npm --workspaces test
      - run: ./test-fixtures-npm

  audit:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces audit --audit-level high
