on:
  pull_request: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces audit --audit-level high

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
      - uses: extractions/setup-just@v2
      - run: corepack enable
      - run: rustup default 1.87.0

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-bindgen-cli@0.2.100

      - run: npm ci
      - run: npm run build --workspaces

      - run: npm --workspaces test --if-present

  test-specifications:
    runs-on: ubuntu-latest
    container: rust:1.87.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
      - uses: extractions/setup-just@v2
      - run: corepack enable
      - run: rustup default 1.87.0

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-bindgen-cli@0.2.100

      - run: npm ci
      - run: npm run build --workspaces

      - run: >
          cargo run 
          --package jns42-tester
          --
          specifications
          --type npm
          --specifications-directory fixtures/specifications
          --output-directory .generated

  test-specifications-async:
    runs-on: ubuntu-latest
    container: rust:1.87.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
      - uses: extractions/setup-just@v2
      - run: corepack enable
      - run: rustup default 1.87.0

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-bindgen-cli@0.2.100

      - run: npm ci
      - run: npm run build --workspaces

      - run: >
          cargo run 
          --package jns42-tester
          --
          specifications
          --type npm
          --specifications-directory fixtures/specifications-async
          --output-directory .generated

  test-cases:
    runs-on: ubuntu-latest
    container: rust:1.87.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
      - uses: extractions/setup-just@v2
      - run: corepack enable
      - run: rustup default 1.87.0

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-bindgen-cli@0.2.100

      - run: npm ci
      - run: npm run build --workspaces

      - run: >
          cargo run 
          --package jns42-tester
          --
          cases
          --type npm
          --cases-directory fixtures/cases
          --output-directory .generated
