on:
  pull_request: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces audit --audit-level high

  test:
    strategy:
      matrix:
        node-version: [22.5.1]
        rust-version: [1.80.0]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: rustup default ${{ matrix.rust-version }}
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-bindgen-cli

      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build --workspaces

      # node test runner seems to support globs since v21
      - if: ${{ matrix.node-version >= 21 }}
        run: npm --workspaces test --if-present

  test-fixtures:
    strategy:
      matrix:
        node-version: [22.5.1]
        rust-version: [1.80.0]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: rustup default ${{ matrix.rust-version }}

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-bindgen-cli

      - uses: actions/checkout@v4
      - run: npm ci

      - run: ./test-fixtures-npm
      - run: ./package-fixtures-npm
