on:
  pull_request: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces audit --audit-level high

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
      - run: corepack enable
      - run: rustup default 1.87.0

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-bindgen-cli@0.2.100
      - run: cargo install just

      - uses: actions/checkout@v4
      - run: npm ci

      - run: just build
      - run: npm --workspaces test --if-present

  fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
      - run: corepack enable
      - run: rustup default 1.87.0

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-bindgen-cli@0.2.100
      - run: cargo install just

      - uses: actions/checkout@v4
      - run: npm ci

      - run: just build
      - run: ./test-fixtures-npm
      - run: ./package-fixtures-npm
