on:
  pull_request: {}
  push:
    branches:
      - "*"
    paths:
      - Makefile
      - package-lock.json
      - .github/**
      - fixtures/**
      - packages/oas/**
      - packages/npm/**

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - run: corepack enable
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces run build
      - run: npm --workspaces test
      - run: ./packages/npm/jns42-generator/test-fixtures

  test-matrix:
    strategy:
      matrix:
        node-version: [21.5.0]
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces run build
      - run: npm --workspaces test
      - run: ./packages/npm/jns42-generator/test-fixtures

  generated-matrix:
    strategy:
      matrix:
        node-version: [21.5.0]
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces run build
      - run: make generated/npm
      - run: npm run test --workspaces

  audit:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm --workspaces audit --audit-level high
