on:
  push:
    branches:
      - "*"
    paths:
      - "*"
      - .github/**
      - fixtures/**
      - projects/rs/**

jobs:
  unit:
    runs-on: ubuntu-latest
    container: rust:1.73.0-alpine3.18
    steps:
      - uses: actions/checkout@v3
      - run: apk add build-base
      - run: cargo test --workspace --all-targets
